import { readEnvFile } from '../env.js';

const env = readEnvFile([
  'MEMORY_ENABLED',
  'MEMORY_LANCEDB_PATH',
  'MEMORY_EMBEDDING_PROVIDER',
  'MEMORY_EMBEDDING_API_KEY',
  'MEMORY_EMBEDDING_MODEL',
  'MEMORY_EMBEDDING_BASEURL',
  'MEMORY_EMBEDDING_DIMENSIONS',
  'MEMORY_EXTRACTION_ENABLED',
  'MEMORY_EXTRACTION_MODEL',
  'MEMORY_EXTRACTION_BASEURL',
  'MEMORY_API_PORT',
  'MEMORY_HOST_GATEWAY',
  'MEMORY_RECALL_LIMIT',
  'MEMORY_HYBRID_ENABLED',
  'MEMORY_BM25_LIMIT',
  'MEMORY_RERANK_ENABLED',
  'MEMORY_RERANK_MODEL',
  'MEMORY_RERANK_BASEURL',
  'MEMORY_SCORE_MIN',
  'MEMORY_SCORE_HALFLIFE_DAYS',
  'MEMORY_CLEANUP_INTERVAL_MS',
  'MEMORY_MAX_PER_SCOPE',
  'MEMORY_DECAY_THRESHOLD',
  'MEMORY_CONSOLIDATION_ENABLED',
  'MEMORY_CONSOLIDATION_SIMILARITY',
  'MEMORY_CONSOLIDATION_MIN_CLUSTER',
  'MEMORY_REINFORCEMENT_FACTOR',
  'MEMORY_MAX_HALF_LIFE_MULTIPLIER',
]);

export const MEMORY_ENABLED =
  (process.env.MEMORY_ENABLED || env.MEMORY_ENABLED) === 'true';

export const MEMORY_LANCEDB_PATH =
  process.env.MEMORY_LANCEDB_PATH ||
  env.MEMORY_LANCEDB_PATH ||
  './data/memory/lancedb';

export const MEMORY_EMBEDDING_PROVIDER =
  process.env.MEMORY_EMBEDDING_PROVIDER ||
  env.MEMORY_EMBEDDING_PROVIDER ||
  'openai-compatible';

export const MEMORY_EMBEDDING_API_KEY =
  process.env.MEMORY_EMBEDDING_API_KEY || env.MEMORY_EMBEDDING_API_KEY || '';

export const MEMORY_EMBEDDING_MODEL =
  process.env.MEMORY_EMBEDDING_MODEL ||
  env.MEMORY_EMBEDDING_MODEL ||
  'Qwen3-Embedding-0.6B-mxfp8';

export const MEMORY_EMBEDDING_BASEURL =
  process.env.MEMORY_EMBEDDING_BASEURL ||
  env.MEMORY_EMBEDDING_BASEURL ||
  'http://127.0.0.1:8000/v1';

export const MEMORY_EMBEDDING_DIMENSIONS = parseInt(
  process.env.MEMORY_EMBEDDING_DIMENSIONS ||
    env.MEMORY_EMBEDDING_DIMENSIONS ||
    '1024',
  10,
);

export const MEMORY_EXTRACTION_ENABLED =
  (process.env.MEMORY_EXTRACTION_ENABLED || env.MEMORY_EXTRACTION_ENABLED) ===
  'true';

export const MEMORY_EXTRACTION_MODEL =
  process.env.MEMORY_EXTRACTION_MODEL ||
  env.MEMORY_EXTRACTION_MODEL ||
  'Qwen3.5-35B-A3B-4bit';

export const MEMORY_EXTRACTION_BASEURL =
  process.env.MEMORY_EXTRACTION_BASEURL ||
  env.MEMORY_EXTRACTION_BASEURL ||
  'http://127.0.0.1:8000/v1';

export const MEMORY_API_PORT = parseInt(
  process.env.MEMORY_API_PORT || env.MEMORY_API_PORT || '12752',
  10,
);

export const MEMORY_HOST_GATEWAY =
  process.env.MEMORY_HOST_GATEWAY ||
  env.MEMORY_HOST_GATEWAY ||
  'host.docker.internal';

export const MEMORY_RECALL_LIMIT = parseInt(
  process.env.MEMORY_RECALL_LIMIT || env.MEMORY_RECALL_LIMIT || '5',
  10,
);

export const MEMORY_HYBRID_ENABLED =
  (process.env.MEMORY_HYBRID_ENABLED || env.MEMORY_HYBRID_ENABLED) === 'true';

export const MEMORY_BM25_LIMIT = parseInt(
  process.env.MEMORY_BM25_LIMIT || env.MEMORY_BM25_LIMIT || '10',
  10,
);

export const MEMORY_RERANK_ENABLED =
  (process.env.MEMORY_RERANK_ENABLED || env.MEMORY_RERANK_ENABLED) === 'true';

export const MEMORY_RERANK_MODEL =
  process.env.MEMORY_RERANK_MODEL ||
  env.MEMORY_RERANK_MODEL ||
  'Qwen3-Reranker-0.6B-mxfp8';

export const MEMORY_RERANK_BASEURL =
  process.env.MEMORY_RERANK_BASEURL ||
  env.MEMORY_RERANK_BASEURL ||
  'http://127.0.0.1:8000/v1';

export const MEMORY_SCORE_MIN = parseFloat(
  process.env.MEMORY_SCORE_MIN || env.MEMORY_SCORE_MIN || '0.05',
);

export const MEMORY_SCORE_HALFLIFE_DAYS = parseFloat(
  process.env.MEMORY_SCORE_HALFLIFE_DAYS ||
    env.MEMORY_SCORE_HALFLIFE_DAYS ||
    '14',
);

export const MEMORY_CLEANUP_INTERVAL_MS = parseInt(
  process.env.MEMORY_CLEANUP_INTERVAL_MS ||
    env.MEMORY_CLEANUP_INTERVAL_MS ||
    '3600000',
  10,
);

export const MEMORY_MAX_PER_SCOPE = parseInt(
  process.env.MEMORY_MAX_PER_SCOPE || env.MEMORY_MAX_PER_SCOPE || '500',
  10,
);

export const MEMORY_DECAY_THRESHOLD = parseFloat(
  process.env.MEMORY_DECAY_THRESHOLD || env.MEMORY_DECAY_THRESHOLD || '0.05',
);

export const MEMORY_CONSOLIDATION_ENABLED =
  (process.env.MEMORY_CONSOLIDATION_ENABLED ||
    env.MEMORY_CONSOLIDATION_ENABLED ||
    'true') === 'true';

export const MEMORY_CONSOLIDATION_SIMILARITY = parseFloat(
  process.env.MEMORY_CONSOLIDATION_SIMILARITY ||
    env.MEMORY_CONSOLIDATION_SIMILARITY ||
    '0.82',
);

export const MEMORY_CONSOLIDATION_MIN_CLUSTER = parseInt(
  process.env.MEMORY_CONSOLIDATION_MIN_CLUSTER ||
    env.MEMORY_CONSOLIDATION_MIN_CLUSTER ||
    '3',
  10,
);

export const MEMORY_REINFORCEMENT_FACTOR = parseFloat(
  process.env.MEMORY_REINFORCEMENT_FACTOR ||
    env.MEMORY_REINFORCEMENT_FACTOR ||
    '0.5',
);

export const MEMORY_MAX_HALF_LIFE_MULTIPLIER = parseFloat(
  process.env.MEMORY_MAX_HALF_LIFE_MULTIPLIER ||
    env.MEMORY_MAX_HALF_LIFE_MULTIPLIER ||
    '3',
);
